spring:
  datasource:
    url: jdbc:sqlite:${shura.cache.directory}/shura.db
    driver-class-name: org.sqlite.JDBC

logging.level:
  root: INFO
  org.hibernate: ERROR
  com:
    bots:
      shura:
        guild: DEBUG

shura:
  cache:
    enabled: true
    updated: true
    directory: cache
  drunk-mode: true
  thresh-hold: 3
  shurapleer:
    enabled: false
    url:
    authentication:
      token-uri:
      client-id:
      client-secret:
      authorization-grant-type:
      scope:
      resource:
      jwk-uri:
  discord:
    token: